### ISSUE TITLE
convert_metagenemark_gff_to_gff3.py produces invalid GFF3

### ISSUE THREAD

**Issue by jonathancrabtree** [jorvis/biocode#33]
convert_metagenemark_gff_to_gff3.py echoes comment lines from MetaGeneMark unchanged. This is a problem when the comment is "##FASTA" (i.e., as part of a predicted polypeptide) GFF3 parsers are required to interpret such a line as the beginning of the GFF3 FASTA sequence section. One possible solution would be to tack on an extra "#" before echoing the comments. The situation is exacerbated by the fact that the current Biocode GFF3 parser will accept any line _starting with_ "##FASTA" (e.g., "##FASTATKAANICDYENLAFMG") as the FASTA section delimiter (issue #32).

**Comment by jorvis** [comment]
I think your proposal was a reasonable one.  I committed 38e612d for this.   Here, I didn't see the harm in prefixing anything starting with ##FASTA so that other parsers don't have the same issue.
