### ISSUE TITLE
To extract longest isoform from trinity assembly

### ISSUE THREAD

**Issue by yogeshgupt** [jorvis/biocode#35]
Dear All,

I GETTING SOME ERROR BY USING 

Dear All,

I am getting some error when using  script: https://github.com/jorvis/biocode/blob/master/sandbox/jorvis/filter_longest_trinity_subcomponents.py

Error:
File "/home/yogesh/biocode/sandbox/jorvis/filter_longest_trinity_subcomponents.py", line 45, in <module>
    import biocodeutils
ImportError: No module named 'biocodeutils'

How Can I resolve it.

Thanks

**Comment by jorvis** [comment]
This is an easy one.  Many of the biocode scripts use internal libraries/modules, and when you executed the script it just couldn't find them.  All you have to do is modify your PYTHONPATH environmental variable to point to the lib directory like this:

export PYTHONPATH = $PYTHONPATH:/home/yogesh/biocode/lib

Or add that to your .bashrc file.

As a general warning though, code in individual developer's 'sandbox' directories isn't guaranteed to be reliable or have undergone extensive testing.  It is reserved for work in progress or code not necessarily "production-ready".  Please continue to provide feedback about if you have any issues.

**Comment by yogeshgupt** [comment]
still getting the error after adding to path :$PYTHONPATH:/home/yogesh/biocode/lib

File "/home/yogesh/biocode/sandbox/jorvis/filter_longest_trinity_subcomponents.py", line 45, in <module>
    import biocodeutils
ImportError: No module named 'biocodeutils'

Please suggest how to resolve it

Thanks and Regards
Yogesh

**Comment by jorvis** [comment]
Can you send the terminal output of this right before you run it?

$ echo $PYTHONPATH
