### ISSUE TITLE
Minor fasta script naming issue

### ISSUE THREAD

**Issue by jonathancrabtree** [jorvis/biocode#38]
The fasta/ subdirectory contains a number of scripts, pretty much all of which deal with multi-FASTA files, rather than single-sequence FASTA files. Most (but not all) of the scripts have "fasta" somewhere in their name, but there's a lone script that uses the term "multifasta" instead, "compare_two_multifastas.pl"

**Comment by jorvis** [comment]
True, thanks for bringing it up.  This was one of the older scripts I brought into the collection (maybe obvious, since it's Perl)
