### ISSUE TITLE
convert_gff3_to_ncbi_tbl.py error generated

### ISSUE THREAD

**Issue by ascendo** [jorvis/biocode#41]
Dear Joshua,

I've got error during convert_gff3_to_ncbi_tbl.py.

Can you please check ?

convert_gff3_to_ncbi_tbl.py  -i ../gene.gff -o aasdasdasd -ln JC0 -nap adsadasd

Traceback (most recent call last):
  File "/Users/wyim/bin/biocode/gff/convert_gff3_to_ncbi_tbl.py", line 92, in <module>
    main()
  File "/Users/wyim/bin/biocode/gff/convert_gff3_to_ncbi_tbl.py", line 55, in main
    (assemblies, features) = biocodegff.get_gff3_features( args.input_file )
  File "/Users/wyim/bin/biocode/lib/biocodegff.py", line 272, in get_gff3_features
    raise Exception("Error in GFF3: Parent {0} referenced by a child feature before it was defined".format(parent_id) )
Exception: Error in GFF3: Parent Mecry000010.1 referenced by a child feature before it was defined

**Comment by jorvis** [comment]
Some of the parsing libraries have issues with misordered GFF.  That is, where features like a CDS appear which reference an mRNA parent, but in which that parent has not been seen yet in the file.  Fortunately, this has come up before and there's a script which attempts to correct for it.  Could you try running your input through the [gff/correct_gff_feature_order.pl](https://github.com/jorvis/biocode/blob/master/gff/correct_gff_feature_order.pl) script and then use that output to try again?

**Comment by jorvis** [comment]
Closing this, assuming that fixed the issue.  If not, please re-open and post example input file.
