### ISSUE TITLE
Can't import things with write_fasta_from_gff.py 

### ISSUE THREAD

**Issue by ktretina** [jorvis/biocode#43]
After trying to run this script with the below command, I was having trouble with important utils/things. I've used this script before (checkout and relevant .bashrc line below), so this must be due to recent changes. I noticed that these modules were in the */biocode/lib/biocode/ sub-directory, so I added that to my PYTHONPATH (below), and got the same error.

$ python ~/git/biocode/gff/write_fasta_from_gff.py -i ref.gff3 -f ref.fasta -o ref.fasta -t cds

Traceback (most recent call last):
  File "/home/ktretina/git/biocode/gff/write_fasta_from_gff.py", line 31, in <module>
    from biocode import utils, gff
  File "/home/jorvis/git/biocode/lib/biocode/gff.py", line 4, in <module>
    from biocode import things, annotation
  File "/home/jorvis/git/biocode/lib/biocode/things.py", line 3, in <module>
    from biocode import utils, gff, tbl
  File "/home/jorvis/git/biocode/lib/biocode/tbl.py", line 3, in <module>
    from biocode import utils, things

***Checkout***
/home/ktretina/git/biocode/

***.bashrc file***
export PYTHONPATH=$PYTHONPATH:/home/jorvis/lib:/home/jorvis/svn/jorvis/utilities/lib:/home/jorvis/git/biocode/lib:/home/jorvis/git/Emergence/emergence/apps:/home/ktretina/git/biocode/lib/biocode/

**Comment by jorvis** [comment]
Note for others reading this, this is a git clone rather than an installation using PyPi.

Kyle - The key directory I don't see in your PYTHONPATH is this:  /home/ktretina/git/biocode/lib

What happens when you add that?

**Comment by ktretina** [comment]
It doesn't seem to make a difference, I still get the same error when I set it to this (below), open a new session, then run the script.

export PYTHONPATH=$PYTHONPATH:/home/jorvis/lib:/home/jorvis/svn/jorvis/utilities/lib:/home/jorvis/git/biocode/lib:/home/jorvis/git/Emergence/emergence/apps:/home/ktretina/git/biocode/lib/biocode/:/home/ktretina/git/biocode/lib

**Comment by jorvis** [comment]
Confused here.  I just spawned a brand-new VM, empty, and did this:

```
jorvis@falcon-node-001:~$ sudo apt-get install git
...
jorvis@falcon-node-001:~$ git clone https://github.com/jorvis/biocode.git
Cloning into 'biocode'...
remote: Counting objects: 3495, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 3495 (delta 0), reused 0 (delta 0), pack-reused 3491
Receiving objects: 100% (3495/3495), 1.08 MiB | 0 bytes/s, done.
Resolving deltas: 100% (2073/2073), done.
Checking connectivity... done.

jorvis@falcon-node-001:~$ export PYTHONPATH=$HOME/biocode/lib

jorvis@falcon-node-001:~$ ./biocode/gff/write_fasta_from_gff.py 
usage: write_fasta_from_gff.py [-h] -i INPUT_FILE [-o OUTPUT_FILE]
                               [-t {protein,cds}] [-f FASTA]
                               [-ft {mRNA,polypeptide}] [--check_ends]
                               [--check_internal_stops]
write_fasta_from_gff.py: error: the following arguments are required: -i/--input_file
```

**Comment by ktretina** [comment]
I tried a series of different additions to my PYTHONPATH, and was able to get a different error:

[ktretina@medusa ~]$ export PYTHONPATH=/home/ktretina/git/biocode/lib/biocode
[ktretina@medusa ~]$ python ~/git/biocode/gff/write_fasta_from_gff.py -i ref.gff3 -f ref.fasta -o ref.fasta -t cds
Traceback (most recent call last):
  File "/home/ktretina/git/biocode/gff/write_fasta_from_gff.py", line 31, in <module>
    from biocode import utils, gff
ImportError: No module named 'biocode'
[ktretina@medusa ~]$ export PYTHONPATH=/home/ktretina/git/biocode:/home/ktretina/git/biocode/lib/biocode/
[ktretina@medusa ~]$ python ~/git/biocode/gff/write_fasta_from_gff.py -i ref.gff3 -f ref.fasta -o ref.fasta -t cds
Traceback (most recent call last):
  File "/home/ktretina/git/biocode/gff/write_fasta_from_gff.py", line 31, in <module>
    from biocode import utils, gff
ImportError: No module named 'biocode'
[ktretina@medusa ~]$ export PYTHONPATH=/home/ktretina/git/:/home/ktretina/git/biocode:/home/ktretina/git/biocode/lib:/home/ktretina/git/biocode/lib/biocode
[ktretina@medusa samples]$ python ~/git/biocode/gff/write_fasta_from_gff.py -i reference/Tparva_Muguga_newref.gff3 -f reference/reference.tp.assembly.all.fasta -o test.fasta -t cds
Traceback (most recent call last):
  File "/home/ktretina/git/biocode/gff/write_fasta_from_gff.py", line 126, in <module>
    main()
  File "/home/ktretina/git/biocode/gff/write_fasta_from_gff.py", line 65, in main
    utils.add_assembly_fasta(assemblies, args.fasta)
  File "/home/ktretina/git/biocode/lib/biocode/utils.py", line 219, in add_assembly_fasta
    fasta_seqs = utils.fasta_dict_from_file(fasta_file)
NameError: name 'utils' is not defined

I'm a little confused by this, because I would expect it to first throw an error at import utils.

**Comment by jorvis** [comment]
Try making your PYTHONPATH only this:

export PYTHONPATH=/home/ktretina/git/biocode/lib

**Comment by ktretina** [comment]
This seems to have done the trick! Thanks!
