### ISSUE TITLE
Structural comparison script deletes all bed files

### ISSUE THREAD

**Issue by jorvis** [jorvis/biocode#5]
I'd like to shift your structural comparison script out of the sandbox and into production, but I did a quick code review and one part at the very end concerned me.  It seems to delete all bed files in the output directory rather than keeping track of the specific temporary bed files it creates and just deleting them.

This certainly isn't an urgent issue, since this is currently a sandbox script.

**Comment by jorvis** [comment]
@priti88 , was this fixed?

**Comment by priti88** [comment]
Yes. its fixed.

On Mon, Mar 23, 2015 at 5:52 PM, Joshua Orvis <notifications@github.com>
wrote:

> @priti88 <https://github.com/priti88> , was this fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jorvis/biocode/issues/5#issuecomment-85216394>.
>



-- 

Priti Kumari
Bioinformatics Software Engineer
Institute for Genome Sciences
University of Maryland School of Medicine
801 West Baltimore St,
Baltimore, MD 21201
410-706-8353
