### ISSUE TITLE
NameError: name 'utils' is not defined

### ISSUE THREAD

**Issue by arsilan324** [jorvis/biocode#53]
I am trying to run convert_gff3_to_ncbi_tbl.py script but getting this error. 
```

ubt80:EMBLmyGFF3 arslan$ python3 convert_gff3_to_ncbi_tbl.py -i juncus.fasta.transdecoder.refined.gff3 -o arslan.tbl -ln TEST -nap JE -gf juncus-rp.fasta
INFO: splitting mRNA off gene Transcript_138016|g.186294
Traceback (most recent call last):
  File "convert_gff3_to_ncbi_tbl.py", line 89, in <module>
    main()
  File "convert_gff3_to_ncbi_tbl.py", line 82, in main
    tbl.print_tbl_from_assemblies(assemblies=assemblies, ofh=ofh, go_obo=args.go_obo, lab_name=args.lab_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/biocode/tbl.py", line 86, in print_tbl_from_assemblies
    print_biogene(gene=new_gene, fh=ofh, obo_dict=go_idx, lab_name=lab_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/biocode/tbl.py", line 117, in print_biogene
    gene_coords = utils.interbase0_to_humancoords(gene_loc.fmin, gene_loc.fmax, gene_loc.strand)
NameError: name 'utils' is not defined

```
Can you please comment how can I fix it?
Thanks

**Comment by jorvis** [comment]
I'm a little confused by that.  Your command line shows you invoking Perl to run the script, but then the stack trace is python.  I'm assuming that is a mis-paste.

I'm not at a spot at the moment where I can edit and test this.  If you open the tbl.py module there and replace each instance of " utils." with " biocode.utils." does this fix the problem?

**Comment by arsilan324** [comment]
I am sorry it was typo. I should have written python3 instead of perl; (fixed now) in the code above.
The code is here
`https://github.com/jorvis/biocode/blob/master/gff/convert_gff3_to_ncbi_tbl.py`

Even replacing utils with utils with biocode.utils in the code doesn't work. Instead it says
`NameError: name 'biocode' is not defined`

**Comment by jorvis** [comment]
Would you mind making your input file available somewhere?  Or you could
email it to me at Gmail with this user name.

**Comment by arsilan324** [comment]
I just wrote you email with the dropbox links..

**Comment by bernt-matthias** [comment]
as a follow up: replacing "utils." with " biocode.utils." does this fix the problem

**Comment by jorvis** [comment]
Thanks for the report.  Corrected in commit 3e095dd

**Comment by eloguh** [comment]
I have the same problem, i can't resolve it, NameError: name 'biocode' is not defined

**Comment by jorvis** [comment]
@eloguh Did you happen to see if your script has the changes from the commit linked above?  If not, maybe you still have the older script version.  There are 4 lines of code that were corrected.

**Comment by eloguh** [comment]
what i did was correct the import

**Comment by jorvis** [comment]
If you're not using a GitHub checkout then you should probably replace your tbl file with this one:

https://raw.githubusercontent.com/jorvis/biocode/3e095dd233dcf3353654f3958b6117a6f2d3ea44/lib/biocode/tbl.py

That's a critical part which uses the module name as needed.

**Comment by eloguh** [comment]
thanks

**Comment by jorvis** [comment]
I'm surprised you're seeing this if you're using an updated version of biocode, as I've made a release since this bugfix was added.

**Comment by eloguh** [comment]
I still do not control much the general operation of the upload of codes
