### ISSUE TITLE
Syntax error on gff.py

### ISSUE THREAD

**Issue by PlantDr430** [jorvis/biocode#55]
Hello,

I was trying to run some of your gff3 statistics and after getting the clone I get a syntax error when it tries to open the gff.py

/Wyka/bioinformatics$ python report_gff3_statistics.py -i Claviceps_purpurea_LM4.gff3 -o output_test
Traceback (most recent call last):
  File "report_gff3_statistics.py", line 19, in <module>
    from biocode import gff
  File "/opt/biocode/lib/biocode/gff.py", line 103
    [*v] = map(unquote, tt[1].strip().split(COMMA))
     ^
SyntaxError: invalid syntax

I am running this on Ubuntu 18.04

**Comment by jorvis** [comment]
Have you tried with Python3?  Biocode has been little tested with Python2.

**Comment by PlantDr430** [comment]
Sorry, I thought I was using python3. It's been a long day, haha. I'll let you know.

**Comment by PlantDr430** [comment]
Totally, works. Again, I'm sorry about that.

**Comment by jorvis** [comment]
No problem at all.  Thanks for using it.
