### ISSUE TITLE
Insert EC numbers into chado database issue

### ISSUE THREAD

**Issue by nsuvarnaiari** [jorvis/biocode#63]
Hi Josh,

I am trying to run your script "insert_ec_number.pl" in chado folder to insert an EC number into chado database. I get the following error,

[snadendla@thanos chado]$ perl insert_ec_number.pl --ec_number=4.3.99.3 --name=7-carboxy-7-deazaguanine synthase --database=hcon2 --user=XXXX --password=XXXX --server=manatee-db --database_type=mysql
attempting to create database connection
INFO: got db_id 8 for name EC
INFO: got cv_id 7 for name EC
Unable to find cvterm_id corresponding to base accession 4.3.99.-.  Check the base term? at insert_ec_number.pl line 283.

I tried adding the base 4.3.99.- but still get the same error as above.

What can I do to insert this EC number?

Thanks,
Suvvi

**Comment by jorvis** [comment]
Whatever loaded the EC numbers initially is supposed to create the full tree of terms.  I can see in that database that there are two terms but no parent:

```
+-----------+-----------+
| cvterm_id | accession |
+-----------+-----------+
|      5846 | 4.3.99.1  |
|      5847 | 4.3.99.2  |
+-----------+-----------+
```

4.3.99.- doesn't exist.  

You mentioned trying to add it and it failing, but I tried and it worked:

```
$ perl insert_ec_number.pl --ec_number=4.3.99.- --name=7-carboxy-7-deazaguanine synthase --database=hcon2 --user=XXX --password=XXX --server=manatee-db --database_type=mysql
attempting to create database connection
INFO: got db_id 8 for name EC
INFO: got cv_id 7 for name EC
INFO: inserting row into dbxref with dbxref_id: 56551
INFO: inserting row into cvterm with cvterm_id: 35952
INFO: inserting row into dbxref with dbxref_id: 56552
INFO: inserting row into cvterm_dbxref with cvterm_dbxref_id: 22208
INFO: inserting row into cvterm_relationship with cvterm_relationship_id: 54222
INFO: got cvterm_id 2 for name is_a
```

You should be able to add the child term now.

**Comment by jorvis** [comment]
Closed for now, please re-open if the child term insertion still fails.

**Comment by nsuvarnaiari** [comment]
Josh,

Thanks for adding the parent.

I do not know why it worked for you and not me. I have few other granular EC numbers for which the parents don't exist to insert them.
Here is the list
7.4.2.8
2.7.14.1
7.1.1.2

So, for 7.1.1.2, I tried adding the parent,

[snadendla@thanos chado]$ perl insert_ec_number.pl --ec_number=7.1.1.- --name=Coenzyme Q reductase --database=hcon2 --user=XX --password=XX --server=manatee-db --database_type=mysql
attempting to create database connection
INFO: got db_id 8 for name EC
INFO: got cv_id 7 for name EC
Unable to find cvterm_id corresponding to base accession 7.1.-.-.  Check the base term? at insert_ec_number.pl line 283.

Thanks,
Suvvi

**Comment by jorvis** [comment]
How was this database initially loaded?  I don't see any EC numbers beginning with a 7.

**Comment by nsuvarnaiari** [comment]
This database was loaded in 2017. The enzyme.dat file used then in the pipeline was 2014 version. At that time I guess there was no EC number with base 7.-.-.-.
