### ISSUE TITLE
convert_augustus_to_gff3.py error

### ISSUE THREAD

**Issue by JingXia730** [jorvis/biocode#64]
Hi,

I used the convert_augustus_to_gff3.py with the code `python3 convert_augustus_to_gff3.py -i RH88_augustus_draft.gff -o RH88_augustus_draft_converted.gff3`

And I got the following error:
`Traceback (most recent call last):
  File "convert_augustus_to_gff3.py", line 179, in <module>
    main()
  File "convert_augustus_to_gff3.py", line 135, in main
    feat_id = gff.column_9_value(cols[8], 'ID')
NameError: name 'gff' is not defined`

I tried run the script directly `./convert_augustus_to_gff3.py -i RH88_augustus_draft.gff -o RH88_augustus_draft_converted.gff3`
but it didn't work.

My python version is python/3.7.0. How can I fix this?

Thanks!!
Jing

**Comment by jorvis** [comment]
Do you mind compressing and attaching your input file?  I don't have any augustus ones currently to test with.

**Comment by JingXia730** [comment]
This is the input file
[Test_augustus.gff.gz](https://github.com/jorvis/biocode/files/3642974/Test_augustus.gff.gz)

**Comment by jorvis** [comment]
Thank you.  And did you install biocode via pip or git checkout?

**Comment by JingXia730** [comment]
No, I just directly run this script. Should I install biocode first?

**Comment by jorvis** [comment]
It's fine to operate from a checkout rather than installing, you just have to modify PYTHONPATH so it knows where to find the modules.  From the README:

cd /opt
git clone https://github.com/jorvis/biocode.git

# You probably want to add this line to your $HOME/.bashrc file
export PYTHONPATH=/opt/biocode/lib:$PYTHONPATH

**Comment by jorvis** [comment]
When I did this the conversion ran fine.  Attaching result.
[test.gff3.gz](https://github.com/jorvis/biocode/files/3642995/test.gff3.gz)
