### ISSUE TITLE
convert_gff3_to_ncbi_tbl.py

### ISSUE THREAD

**Issue by stanislasmorand** [jorvis/biocode#66]
Dear Joshua Orvis & the team,
I am a beginner in bioinformatics so please excuse my wording ;-)
I downloaded your biocode-master.zip onto our linux server, unzipped it and tried to initiate the script (from /home/stanislasmorand/BIOCODE/biocode-master/gff) **convert_gff3_to_ncbi_tbl.py** with just this command line (w/o providing essential arguments such as input GFF file, input FASTA file nor output directory address) :
$ python3 convert_gff3_to_ncbi_tbl.py
Here is the error message I received : 
`[08:51] morands@frrdcim20: gff $ python3 convert_gff3_to_ncbi_tbl.py`
`Traceback (most recent call last):`
 ` File "convert_gff3_to_ncbi_tbl.py", line 36, in <module>`
  `  from biocode import utils, gff, things, tbl`
`ModuleNotFoundError: No module named 'biocode'`
I guess I omitted to install another package to make it run adequately. 
Could you please indicate me what is missing or what is wrong in my biocode installation?
Thanks in advance for your precious time & help.
Kindest regards,
Stan

**Comment by jorvis** [comment]
Stan -

You should probably check the install instructions [here](https://github.com/jorvis/biocode).  Search for "Getting the code".  The easiest install method is just the one-line command using pip3, but if you download it directly from GitHub as you did you'll need to modify your ~/.bashrc file and add a PYTHONPATH to point to where you installed the code.  This will allow the internal libraries to be found.

**Comment by stanislasmorand** [comment]
Thanks, indeed my PYTHONPATH was not correctly updated. Cheers ! Stan
