### ISSUE TITLE
Python upgrade/conversion? 

### ISSUE THREAD

**Issue by RPINerd** [jorvis/biocode#82]
Are you interested in having the other perl code translated to python? Or any of the python code updated to 3.11? Anything stuck on 2.7 because of some tedious dependency?

**Comment by jorvis** [comment]
I don't mind any of the .pl scripts being reimplemented in .py, but both could live side-by side.

Also, if you find anything stuck on 2.x I'd love to see it reworked for 3.10+

Closing this for now and any tickets with specific issues/scripts could be opened.
